SELECT * FROM pos.item;

INSERT INTO item VALUES (DEFAULT, "BigMac", 4.49, "BigMac.jpg");
INSERT INTO item VALUES (DEFAULT, "QPC", 4.49, "QPC.jpg");
INSERT INTO item VALUES (DEFAULT, "QPC W/ Bacon", 5.59, "QPCWBacon.jpg");
INSERT INTO item VALUES (DEFAULT, "QPC Deluxe", 6.99, "QPCDeluxe.jpg");
INSERT INTO item VALUES (DEFAULT, "Crispy Chicken", 4.49, "CrispyChicken.jpg");
INSERT INTO item VALUES (DEFAULT, "Spicy Crispy Chicken", 4.99, "SpicyCrispyChicken.jpg");
INSERT INTO item VALUES (DEFAULT, "Crispy Chicken Deluxe", 5.89, "CrispyChickenDeluxe.jpg");
INSERT INTO item VALUES (DEFAULT, "Spicy Crispy Chicken Deluxe", 5.99, "SpicyCrispyChickenDeluxe.jpg");
INSERT INTO item VALUES (DEFAULT, "Fish Fillet", 4.49, "FishFillet.jpg");
INSERT INTO item VALUES (DEFAULT, "4 Nuggets", 1.00, "4Nuggets.jfif");
INSERT INTO item VALUES (DEFAULT, "6 Nuggets", 3.99, "6Nuggets.jfif");
INSERT INTO item VALUES (DEFAULT, "10 Nuggets", 5.99, "10Nuggets.jpg");
INSERT INTO item VALUES (DEFAULT, "20 Nuggets", 11.99, "20Nuggets.jfif");
INSERT INTO item VALUES (DEFAULT, "Hamburger", 2.29, "Hamburger.jpg");
INSERT INTO item VALUES (DEFAULT, "Cheeseburger", 2.49, "Cheeseburger.jpg");
INSERT INTO item VALUES (DEFAULT, "Coke", 1.00, "Coke.jpg");
INSERT INTO item VALUES (DEFAULT, "Diet Coke", 1.00, "DietCoke.png");
INSERT INTO item VALUES (DEFAULT, "Sprite", 1.00, "Sprite.jpg");
INSERT INTO item VALUES (DEFAULT, "Fanta Orange", 1.00, "FantaOrange.jfif");
INSERT INTO item VALUES (DEFAULT, "Iced Tea", 1.00, "IcedTea.jfif");
INSERT INTO item VALUES (DEFAULT, "Sweet Tea", 1.00, "SweetTea.jfif");
INSERT INTO item VALUES (DEFAULT, "Coffee", 1.00, "Coffee.jfif");
INSERT INTO item VALUES (DEFAULT, "Coffee Decaf", 1.00, "CoffeeDecaf.jfif");
INSERT INTO item VALUES (DEFAULT, "Hawaiian Punch", 1.00, "HawaiianPunch.jfif");
INSERT INTO item VALUES (DEFAULT, "Fanta Straw", 1.00, "FantaStraw.jpg");
INSERT INTO item VALUES (DEFAULT, "Dr. Pepper", 1.00, "DrPepper.jpg");
INSERT INTO item VALUES (DEFAULT, "Orange Juice", 1.00, "OrangeJuice.jfif");
INSERT INTO item VALUES (DEFAULT, "Dasani Water", 2.29, "DasaniWater.jfif");